### ISSUE TITLE
[proposal]: improve how the controller passes config to workers

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1038]
Currently, the controller passes most configuration to a worker through environment variables set on the worker's container. _Some_ configuration, however, is obtained by the worker through an alternative channel-- _it must use the k8s API to locate and read the project secret._

At minimum, the worker could be spared some effort by the controller mounting the project secret to the file system. This lowers the bar for what is expected of custom workers _and_ possibly moves us toward further restricting permissions on workers to make Brigade more secure on the whole.

Better still, we could consider consolidating the two methods through which the controller passes configuration to the worker so that we don't have _some_ set as environment variables and other configuration passed in via a secret.

**Comment by vdice** [comment]
A quick +1 on this.  Consolidation of context/config transmission (and perhaps making sure it is all 'pushed' to the worker, rather than it needing to fetch add'l info) is bound to bring benefits of simpler and less-fragile code.  As some of the information is non-trivial (i.e., not easily/efficiently transmitted via an env var), perhaps unification around mounts are in order.

**Comment by krancour** [comment]
This has already been incorporated into 2.0. Closing.
