### ISSUE TITLE
[proposal] Generic Gateway: The secret should be stored as a secure hash instead as a string 

### ISSUE THREAD

**Issue by danmx** [brigadecore/brigade#1041]
Generic gateway secret should be stored securely as a [hash](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#leverage-an-adaptive-one-way-function) (e.g. Argon2).

**Comment by krancour** [comment]
I agree that secrets at rest should be stored as secure hashes instead-- at least in the cases where you never need the original secret again and only ever need to compare the hash you've stored to the hash you've computed from a secret provided by another party. And that _is_ the case here.

This would be a breaking change, however, so I'm going to label this as something we'll look at in 2.0.

**Comment by radu-matei** [comment]
Same comment as [in the previous issue about authentication in the generic gateway](https://github.com/brigadecore/brigade/issues/1040#issuecomment-563045130) - I think we can address this issue without a breaking change, by incrementing the version in the event path, and keeping v1 with the current behaviour.

**Comment by krancour** [comment]
@radu-matei but we're talking only about an API path, right? This is a field on the project type and we'd be changing what we store in that field.

**Comment by danmx** [comment]
@krancour why is it github-specific? It's about secret storage. It shouldn't be stored in plain text.

**Comment by krancour** [comment]
@danmx I mispoke.

> The 2.0 proposal will include the removal of GitHub-specific support from Brigade's core

I incorrectly referenced the GitHub gateway when I intended to reference the generic gateway. The proposal will remove _all_ gateway-specific support from the core.

> It's about secret storage.

Not all secrets can be stored as secure hashes. That works well for passwords, but many secrets eventually need to be reused in their original, unencrypted form. So this issue isn't really generically about secrets. It's about specific sorts of secrets, which are disappearing from Brigade 2.0.

The issue does remain relevant to 1.x, which is why it remains open.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
