### ISSUE TITLE
[proposal]: A manual input step in the project

### ISSUE THREAD

**Issue by danmx** [brigadecore/brigade#1043]
A manual input/configmation step would be useful in some types of workloads.

For example it could be implemented by adding a `service` (ingress+service+deployment) to `Brigade.js API` or by combination of dependecies in a project trigger (an event from another project + generic gateway with an extra input or one time secret).

**Comment by radu-matei** [comment]
Hi, @danmx!
I'm not sure I totally understand your request - would it mean waiting for a confirmation before executing an event / job?

**Comment by danmx** [comment]
Hi, @radu-matei 
Yes, this would be useful to when building more complex workflows on top of Brigade as an alternative to e.g. Airflow or Argo Workflows (Kubernetes native with a proper programming language for workflow definition).

**Comment by krancour** [comment]
I understand what's being asked for here. I have personally, for instance, often incorporated such a step in CircleCI workflows wherein a maintainer needs to manually approve workflow execution. (I should point out that _IF_ all you looking to do is have maintainers approve CI workflows before execution, there are some GH gateway settings that can be tweeked to more or less enable this.)

In more general terms, implementing this would would raise a whole crop of new questions about how to secure the "confirmation" steps since it was proposed that they will be exposed externally through appropriate service and/or ingress. You wouldn't want just anyone giving confirmation, after all.

Depending on what your exact needs me be, I am wondering if a custom gateway might actually be in order. Imagine, for instance, a gateway that "holds" events for approval instead of immediately and unconditionally emitting them into Brigade. Thoughts?

**Comment by danmx** [comment]
I think a custom gateway that supports one-time links could solve it

**Comment by mumoshu** [comment]
One more alternative I can suggest is that writing a custom K8s operator for e.g. `Approval` custom resources.

You'd create a new `Approval` from your brigade build and let the build wait/block until the approval becomes `Approved` by polling its status. Another process can modify the approval status to `Approved` in reaction to some human interaction or a webhook event. One example of such process would be a custom webhook gateway.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
