### ISSUE TITLE
proposed feature: enable modification of project configuration via brig CLI

### ISSUE THREAD

**Issue by cscheib** [brigadecore/brigade#1044]
If you use the `brig` CLI to create projects, you don't have many options for adding values (ex: sshKey) after initial creation.

The options as I currently see them are:
* using `brig` CLI:
  - `brig project get org/project-name > project.json`
  - edit the json to include your desired values
  - `brig project delete org/project-name`
  - `brig project create -f project.json -x`
* using `kubectl`: 
  - `kubectl edit secret brigade-projectid`
  - add/modify additional values in plaintext under the stringData top-level key, rather than data, allowing the API to base64 encode the values.
  - OR: base64 encode the values yourself, and add them to the data key.
* use the helm chart to create projects.
  - this chart has all of the hooks to get/set/modify values built in already
  - this method is considered deprecated, so it probably shouldn't be used/recommended

Proposals:
* create `brig project edit` verb that bring up the project in $EDITOR, similar to `kubectl edit`
* create `brig project get-value` and `brig project set-value` verbs
* create a helm-like `--set` flag on one or more of the existing verbs

This probably isn't a huge deal once you've got a project established and working, but I'm currently in the experimentation phase, and the effort required to add/modify a value seems higher than it should be.

I realize this may be nullified by whatever v2.0's configuration document/mechanism is, but project modification should still be a consideration going forward.

**Comment by krancour** [comment]
You are correct about what the current options are for editing project configuration and I agree they are inadequate and something better is called for.

> I realize this may be nullified by whatever v2.0's configuration document/mechanism is, but project modification should still be a consideration going forward.

If you're referring to the growing consensus that project configuration may not be stored as k8s secrets in 2.0, that won't nullify this feature request. I think it will make it all the more imperative, since there's obviously no way that we would ever want a user's only recourse for editing project configuration to begin with having credentials for the database and logging in to modify records directly.

**Comment by radu-matei** [comment]
And I don't necessarily think this is a 2.0 feature - as we're adding functionality to `brig`, if we want to prioritize this, I think it can be part of a 1.x release.

**Comment by krancour** [comment]
Ya. Sorry... I actually hadn't intended to make it appear that this issue couldn't be addressed prior to 2.0. I added the 2.0 label because I see it as an issue that would _have to be_ addressed for 2.0. i.e. It _could_ happen sooner. I'm removing the label to hopefully avoid confusion.

**Comment by vdice** [comment]
+1 @cscheib (and others here): the current project management functionality presented by `brig` is lacking, for the reasons mentioned above.  I like all of the issue author's proposed improvements mentioned in the description.

As mentioned in other issues, I am guilty of maintaining the Helm chart workflow for project management.  I probably will continue to do so for some time, as this is how the other Brigade components and config are managed (server, gateways, Kashti, etc.)  I wonder if we were remiss in declaring project management via Helm chart as deprecated?  Perhaps we should revise the documentation to make it clear it continues to be a valid approach, assuming k8s/Helm familiarity, despite `brig` being the preferred approach, presumably as it represents a friendlier interface to those not as comfortable with k8s/Helm.

**Comment by krancour** [comment]
This is well covered by the [2.0 proposal](https://github.com/brigadecore/brigade/tree/master/2.0-PROPOSAL), which has been ratified and is now guiding the 2.0 development effort.

As to any possibility of improving the project management UX in 1.x, my estimate of the effort involved probably rules it out since most of our development resources are now committed to 2.0.
