### ISSUE TITLE
How to cancel previous running jobs for same repository?

### ISSUE THREAD

**Issue by Raffo** [brigadecore/brigade#1048]
Hi, 
I'm trying to understand if I could use brigade to implement the following workflow:

- one job is already running, triggered by a push to a GitHub repository
- another commit is pushed, triggering a new event
- before starting the job for a new event, the previous running job is terminated 
- once the old job is terminated, the new one is started, allowing for only one job (the latest) at any given time.

Not knowing brigade really well, I'm not sure of which part should be modified to allow that. Would a brigade.js file be able to do those actions? Or would it make more sense to write a custom gateway and possibly use some external state or just the kubernetes API? 

Thank you in advance for taking a look at this 😄

**Comment by radu-matei** [comment]
I think you could implement such a workflow without modifying Brigade at all - when handling every push event, you could check if there is an existing event being executed for the project, and delete them (`brig build delete-all` given the project ID).

Would that work for your use case?

**Comment by krancour** [comment]
@radu-matei that would work, but that delete would take completed builds with it, wouldn't it?

(Also, to kill the running builds, this will need the `--force` flag.)

I'm wondering two things:

1. Would a variant of the `brig build delete-all` command (i.e. a new flag) for deleting _only_ running builds for the given project ID be a useful new feature?

1. This concern seems common enough. While this wouldn't satisfy @Raffo's use case perfectly, I wonder if he could get something closely approximating what he wants by adding support for a configurable "quiet period" to the GH gateway. Events wouldn't be emitted immediately into Brigade, rather they'd be held for a bit until some bit of time has elapsed with no competing events having arrived.

**Comment by Raffo** [comment]
@radu-matei I think what @krancour proposes with the point 1 would be better, deleting only the running builds would be the best. 

What I'm proposing is really a feature that is implemented in some CI systems and I think it would be great for brigade. This would allow users to implement workflows that don't allow multiple parallel runs (i.e. in case of side effects to external systems). 

I would be happy to help with a possible implementation, but I guess I would need a few more hints, at this time I don't even understand how a brigade event could actually have the rights and access to `brig` to do `brig build delete-all --running` (or equivalent).

**Comment by krancour** [comment]
@Raffo you would use a job that uses an image that has brig on it and configure the project to use a specific k8s service account that has appropriate permissions.

**Comment by Raffo** [comment]
@krancour so this could theoretically be done with `kubectl` only, finding running pods and running `kubectl delete pod $POD_NAME` on each of them. It wouldn't be as easy to implement, but probably doable.

**Comment by krancour** [comment]
> but we would have no guarantee of only processing the latest

@Raffo can you clarify what you mean by that?

Here's how I would do this:

```
for build in $(brig build list $project -n $namespace | grep Running)
do
  brig build delete $build -n $namespace --force
done
```

(fwiw, I am doing this with `brig` instead of `kubectl` because if using `kubectl` to go after running pods directly, I'd have had my work cut out for me to identify corresponding build IDs so that I can then delete corresponding build secrets. Using `brig build list` and `brig build delete` inverts that process-- starting from running builds and going from there. The corresponding pods automatically get killed by Brigade. This was just easier.)

Revisiting the clarification I requested from you above... Is your concern that this could take out running builds that you want to keep running? For instance, you've received two push events and you want to cancel the build triggered by the first and only run the second, but _don't_ want to cancel any running jobs that might have been triggered by _other_ events, such as new PRs?

**Comment by Raffo** [comment]
> @Raffo can you clarify what you mean by that?

Yeah I meant that jobs are not in a queue or anything like that, so it can be that multiple jobs start roughly at the same time and the "wrong" one cancels the latest one. It's a minor concern I would say and I don't think that brigade's architecture can solve that. If in this case we are talking about something similar to CI builds, that could be solved by talking back to the repo's API and having the job figuring out if it refers to the latest commit. 

>  For instance, you've received two push events and you want to cancel the build triggered by the first and only run the second, but don't want to cancel any running jobs that might have been triggered by other events, such as new PRs?

I wasn't considering this scenario, but the trick about checking the event payload is definitely generally helpful 👍 


I think I have the information I need to start play with brigade a bit more with this use case, let me know if we want to close this issue or if you feel there's more to learn from this case or to enhance brigade or just brig the CLI.

**Comment by krancour** [comment]
> let me know if we want to close this issue or if you feel there's more to learn from this case or to enhance brigade or just brig the CLI.

We can keep this open for now. I think there are some things in here that are potentially informative as we begin to contemplate architectural change in an eventual 2.0.

**Comment by krancour** [comment]
> The OP's request becomes something like `brig event cancel -p my-project --running`

Things have worked this way in the `v2` branch for some time now.

The actual command would be:

```
$ brig event cancel-many -p my-project --running
```

Having said that, there's an element to the original request that doesn't make sense in the context of 2.0. (And it might not have made sense with respect to 1.x either and may have been overlooked.)

Since events are handled _asynchronously_ in both 1.x and 2.0 _and_ because 2.0 also uses queues and configurable caps on the max number of concurrent workers and concurrent jobs (for the sake of resource management), a worker or job responding to a _newer_ event might actually be _blocked_ by a worker or job responding to an older event. That makes it unreliable proposition for the worker or jobs for a newer event to kill workers or jobs for older events, because depending on configuration and event volumes, the newer stuff may be blocked by the older stuff, meaning the newer stuff doesn't get an opportunity to nuke the older stuff.

Closing.
