### ISSUE TITLE
Pods are not coming up after installing Brigade using Helm

### ISSUE THREAD

**Issue by vinod827** [brigadecore/brigade#1097]
Hi,

I'm using **helm v3.2.4** and I tried installing brigade on my Macbook pro using below command : -
`helm install brigade brigade/brigade --set rbac.enabled=false --set vacuum.enabled=false --set api.service.type=LoadBalancer --namespace=brigade`

I can see pods but in the pending state - 

```
**NAME                                    READY   STATUS    RESTARTS   AGE
brigade-brigade-api-df4696fcb-w2xp4     0/1     Pending   0          20m
brigade-brigade-ctrl-744b54c6f4-dldxg   0/1     Pending   0          20m
brigade-kashti-6c47684c5f-4ql5m         0/1     Pending   0          20m**
```

I tried deleting the namespace and re-installing over again but the same result only. Pods are not coming up.

Secondly, as per given documentation this command is not working` helm install brigade/brigade --name brigade-server`. I get this **Error: unknown flag: --name**

I believe the above command do not support latest Helm

Please assist me. Thanks

Output of `brig version`:  - 

Output of `kubectl version`: v1.16

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

**Comment by krancour** [comment]
Hi @vinod827 this has all the appearance of being a deeper Kubernetes problem and not a Brigade problem. Can you do a `kubectl describe` on those pending pods and look at status to find out what's going on?

> Secondly, as per given documentation this command is not working `helm install brigade/brigade --name brigade-server`. I get this Error: unknown flag: --name

Yes. That is indeed a Helm 2 command. We should probably open a separate issue about because I'm sure there are a lot of spots throughout the documentation where we could stand to note which major version of Helm is assumed or even show the equivalent commands for both 2.x and 3.x. Feel free to open such an issue.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
