### ISSUE TITLE
Brigade controller stops processing events

### ISSUE THREAD

**Issue by emilwangaa** [brigadecore/brigade#1115]
Hi,

We are currently having problems with the brigade-ctrl not picking up events. If I restart the pod it works for around 5 minutes and then it just stops processing events without logging any errors. It has worked fine until recently (broke around 11th of august) on both our clusters. We haven't done any changes to the RBAC roles or upgraded Brigade or Kubernetes.

I've tried to remove the Helm chart and install it again and also tried to downgrade to 1.3 - but without any success.
Oh, and one more observation - the api also stops working sometimes and returning an 404 error for endpoints like /v1/projects-build. It doesn't break as often as the ctrl though. This can also be fixed via a restart but it sometimes just fixes itself. 

I've attached the logs from the controller at a time when it has stopped processing events - but it doesn't reveal much. I've also attached the logs from the api at a time when it starts returning 404 for the /v1/projects-build endpoint and then after a while it returns 200 again.

I've also enabled logging from the kubernetes api-server but it hasn't provided any useful information either.

Does anyone have any suggestions to try? Is there some more logging we can enable for the controller or api?

Our current workaround is a CronJob that restarts the controller deployment every 5 minutes and the api deployment every 20 minutes and it keeps us floating for now but is of course not a long term solution

Output of `brig version`: 1.4.0

Output of `kubectl version`: 1.15.11

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

[logs-from-brigade-in-brigade-brigade-api-6b696d7669-5qdf4 (1).txt](https://github.com/brigadecore/brigade/files/5088800/logs-from-brigade-in-brigade-brigade-api-6b696d7669-5qdf4.1.txt)
[logs-from-brigade-in-brigade-brigade-ctrl-7894cf9b45-pvkld.txt](https://github.com/brigadecore/brigade/files/5088801/logs-from-brigade-in-brigade-brigade-ctrl-7894cf9b45-pvkld.txt)

**Comment by krancour** [comment]
Two things I am curious about:

1. Do you think anything else of consequence may have changed in your clusters recently? For instance, introduction of a service mesh? I ask because my first impulse is to say something underneath Brigade sounds broken.

2. Out of curiosity, are you dealing with very event large volumes? Has there been any change in event volume in/around the timeframe you mentioned?

**Comment by emilwangaa** [comment]
Thx for taking you time to answer.

1. We are running Istio but has done that for more than a year and it is disabled for the namespace that hosts all our brigade stuff. The last "major" update we did in regards to brigade was to introduce brigade.json instead of local dependencies in several of our projects - but it has been running smooth for more than a month.

2. No, we are not dealing with very large event volumes - and even lower in the timeframe because of holidays.

**Comment by krancour** [comment]
@emilwangaa a few things here.

First, it's not obvious, but the API is only used by Kashti and nothing else. CLI, gateways, etc. don't talk to it. (This is going to change in Brigade 2.0, but in the current state, this is the case.) Just throwing this out there so that you are aware that without the API server running, only Kashti is affected-- nothing else.

The controller being down is a much larger problem. The thing that the Brigade API and the Brigade controller have in common, of course, is that they both talk to the k8s API server... something is going wrong there in regard to listing/watching Secrets (Brigade events are just Secrets).

I know you said your request volumes are _not_ large, but has there been a large accumulation over time of completed events (Secrets)? i.e. Is the vacuum not running or is it configured to retain a large number of events? We've never seen that be a problem before, but I'll be honest in saying that I don't know how very large numbers of resources might, in general, break k8s list/watch.

**Comment by emilwangaa** [comment]
We don't have a large accumulation of completed events - one of our affected clusters is our playground cluster which is being recreated often and doesn't get many requests. We haven't adjusted the default settings for the vacuum and it's running every hour.

But the fact that both the API and the controller talk to the k8s API server made me think that it might be our firewall playing tricks on us. All egress traffic from our cluster - also traffic to API server - runs through the firewall and it has previously caused issues for us. So I will check with our Ops team if this could be the case.

**Comment by emilwangaa** [comment]
So this issues was related to our firewall and had nothing to do with brigade. Closing issues.
