### ISSUE TITLE
Any tips in how not to write js in yaml?

### ISSUE THREAD

**Issue by tomfotherby** [brigadecore/brigade#1116]
_Warning: Beginner question (feel free to delete if not appropriate, or this is the wrong place to ask)..._

I've been taking Brigade for a spin and I've been enjoying it. One thing that bugs me a little is that I've been writing Javascript inside yaml. What I mean is that my `brigade.js` file looks like this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: myproject
  namespace: brigade
data:
  brigade.js: |-
    const { events, Job, Group } = require("brigadier");
    events.on("exec", function(e, project) {
       ...
       // lots of js code
       ...
    })
```

My workflow is:

1. Make some code changes, writing javascript inside a `ConfigMap`.
1. Apply my changes: `kubectl apply -f myproject-js-config.yaml`
1. Run my project: `brig run myproject`
1. Check logs, debug
1. Go to 1. 

It's a bit ugly writing JS in yaml. My editor can't syntax highlight and the indentation gets weird.  Does anyone have a tip on how I can write my code in a file called `brigade.js` and then easily put that file in a ConfigMap?

**Comment by krancour** [comment]
What you're doing is one of a few approaches that is common only in cases where source code isn't being stored in a git repository somewhere.

If your code _is_ in a git repository, then you should, through project-level configuration, be able to pull `brgiade.js` (a real, honest-to-goodness) JS script from source control. This is, by far, the most common use and should be well-covered by the docs.

Are you deliberately not keeping your `brigade.js` in source control?

**Comment by tomfotherby** [comment]
> ... should be well-covered by the docs.

Thanks, you're right, in the [Scripting Guide docs](https://docs.brigade.sh/topics/scripting/) I found the answer which improved my workflow. I moved my `brigade.js` code out of the `ConfigMap` and into a actual `brigade.js` file and now run my project with:

    brig run --file brigade.js create-reportsdb

But, my question still stands. let me explain...

It's my first brigade script. I'm migrating a 450 line [aws data-pipeline](https://aws.amazon.com/datapipeline/) workflow to brigade and it's going to take some days. It's a ETL pipeline which clones a Mysql Database and removes all <abbr title="Personally Identifiable Information">PII</abbr> so developers can work with production-_like_ data in their test environments. I fully intend to commit to git once its working. But I was going to commit the Kubernetes resources, i.e. the `ConfigMap` that has the `brigade.js` in it together with (sealed-)secrets and other configmap which give the script it's variables. The idea is to have all kubernetes manifests commited to git so we can restore our cluster from scratch declaratively.

My brigade script isn't anything to do with CI/CD, so will probably use `job.useSource = false` so I was planning to commit it in our git repo that has our Kubernetes manifests. Maybe it's more normal to use brigade for CI/CD in which case I can understand commiting the `brigade.js` in the git repo that has the code it is testing, but it's not the case for me.

So, I guess I can work with it in a `brigade.js` file until I'm ready to commit, then move it into the ConfigMap and commit it. But it would be good to have the best of both worlds. In the meantime, a `Makefile` could make the ConfigMap, by copying the contents of `brigade.js` file, or we could use `kubectl kustomize`... Need to look into that.

**Comment by krancour** [comment]
>```
>brig run --file brigade.js create-reportsdb
>```

Forgot about that. That's a good way to proceed as you hack away.

> I'm migrating a 450 line aws data-pipeline workflow to brigade and it's going to take some days.

I'm not sure that we would recommend using Brigade for this purpose. Brigade is not intrinsically able to resume incomplete workflows where it left off. i.e. If you expect this to run for _days_ and something goes wrong, an awful lot of progress could be lost-- _unless_ your workflow itself takes great care to account for making the whole process resumable.

I guess it's worth asking what the benefit of using Brigade is here. Recall that Brigade is _event-drive_ scripting for Kubernetes. What is the event that precipitates this days-long process? In my imagination, you're running this infrequently, perhaps manually, on an ad-hoc basis and not in response to some event.

Unrelated...

> My brigade script isn't anything to do with CI/CD, so will probably use job.useSource = false so I was planning to commit it in our git repo that has our Kubernetes manifests.

Brigade is good for CI/CD, but was definitely not conceived specifically for that purpose. Indicating that a job utilizes some source code (even it's it's only your `brigade.js` script) doesn't inherently conflict with the non-CI/CD nature of what you're doing.

The question of whether Brigade is appropriate for the use case notwithstanding, there's nothing wrong with keeping your `brigade.js` _and_ a copy of the Secret manifest that defines the project all in a git repo. (Storing a copy of that manifest isn't entirely unusual for people who want to be able to pick up their project and plop it down in a different cluster. Just take care that all your secrets are guarded appropriately.) But do consider allowing that Secret manifest that describes the project to include the necessary configuration to source `brigade.js` _from_ that same git repo (instead of embedding it _in_ the secret). By doing this, as the script in the repo changes going forward, no additional manual step is required to make your project use the latest version of it. It will always just pull the latest version of the script from git.

**Comment by tomfotherby** [comment]
@krancour  Thanks for your advice.

> I'm migrating a 450 line aws data-pipeline workflow to brigade and it's going to take some days.

Sorry, I meant it's going to take me some days to migrate the YAML code to Brigade Javascript, not that the Brigade Build would take days to run. It'll take about 5 hours to run the Build. It's cloning a RDS Aurora database, running a few SQL scripts on the clone and altering a Route53 record so users of the database connect to the latest database copy.

Thanks for warning me Brigade isn't recommened for this purpose. I understand it's not a Workflow engine like Argo. I've been enjoying the experience so far. Adding retry loops to Jobs was ok. I wanted to try Brigade out, I'll keep a open mind whether it's the right tool for the Job. Thanks again.

**Comment by tomfotherby** [comment]
I've finished my `brigade.js` - it's a 600 line monster that creates over 50 Pods. It works really well and I totally love Brigade :heart: . I love the simplicity of having everything stored as a secret.

Anyway, I can answer my own question now.

> Does anyone have a tip on how I can write my code in a file called `brigade.js` and then easily put that file in a ConfigMap?

Yes, Create a file called `kustomization.yaml` that contains:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: brigade

configMapGenerator:
- name: create-reportsdb
  files:
  - brigade.js

# generatorOptions modify behavior of all ConfigMap and Secret generators
generatorOptions:
  # disableNameSuffixHash is true disables the default behavior of adding a suffix to the names of generated resources that is a hash of the resource contents.
  disableNameSuffixHash: true
```

Usage:

1. Generate the configmap.yaml: `kubectl kustomize > create-reportsdb-js-config.yaml`
1. Apply the created configmap: `kubectl apply -f create-reportsdb-js-config.yaml`
1. Configure the `create-reportsdb` Brigade _Project_ to use this configmap as the default `brigade.js` file (if no script is supplied when it gets an event). This is usually done as part of "brig project create", but can be done later by editing the Brigade Project, stored as a kubernetes secret.

This gives the best of both worlds:

1. While developing `brigade.js` you can have it in a real file called `brigade.js` and trigger a build using the latest copy: `brig run --file brigade.js create-reportsdb`
1. When you have a working copy, you create a `ConfileMap` with `brigade.js` embeded using the above kustomize technique.

Sorted! :heavy_check_mark:
