### ISSUE TITLE
Specify group-id when manually triggering a job

### ISSUE THREAD

**Issue by stavalfi** [brigadecore/brigade#1128]
Brigade has a feature of triggering jobs manually using REST api. I think that it's desired to know the relation of the jobs so we (`we` = the users of Brigade) can better manage them as groups.

For example:

* Job-1,2 belongs to task-1
* Job-3 belongs to task-2
* Job-4,5 belongs to task-3
* Job-1,5 belongs to task-4

What can we do with them:

- Canceling task-2 will result in canceling job-3.
- Canceling task-1 will result in canceling job-2 but not job-1 because it is being use in task-4 as well.
- Requesting the status of task-3 will return the status of job-4,5.

To be able to acheive that, we need a way to specify the relation (`group-id`) of every brigade-job when triggering them. 

Notes:

* `cancel-brigade-job` terminolegy is not defined in this feature-request but should be defined by Brigade in a sepeate issue.

**Comment by krancour** [comment]
@stavalfi 

> Brigade has a feature of triggering jobs manually using REST api.

I'm afraid that isn't true. Brigade 1.x has no REST API except for a read-only API that is used exclusively by Kashti (the dashboard). All components of Brigade 1.x talk _directly_ to the Kubernetes.

> Job-1,2 belongs to task-1

_What's a task, exactly?_ This isn't a concept that exists in Brigade currently. This PR is trying to redefine the entire domain model. 😉 

Reading between the lines, it seems to me that what you really want is to group jobs together as some independent, atomic unit of management smaller than a build? Builds are composed of tasks and tasks are composed of jobs? Again-- that's a _giant_ change to the domain.

The "simple" answer is to have more builds.

* Job-1,2 belongs to __build-1__
* Job-3 belongs to __build-2__
* Job-4,5 belongs to __build-3__
* Job-1,5 belongs to __build-4__

I put "simple" in quotes because depending on where the events are coming from and what gateway is brokering those events, this might be easier said that done.

fwiw, Brigade 2.0 should make it considerably easier to trigger multiple workflows from a single event (we've done away with the term "builds" because it smells like CI and we don't want to be typecast only as a CI platform).

I hope you can appreciate that with most of our development efforts currently focused on 2.0, changes to 1.x as sweeping as what I believe you are proposing aren't really on the table.

I'd be happy to give further guidance on how you can accomplish this with a custom gateway.

**Comment by stavalfi** [comment]
@krancour 

thanks for the great comment. you are a good reader between the lines ;)

---

> Brigade 1.x has no REST API 

https://docs.brigade.sh/intro/quickstart/#send-a-simpleevent-to-the-generic-gateway



---

I have just started to learn brigarte so I have much to learn before commenting again. I may use this thread in the future, but for now. it's good enough.

Thanks 👍

**Comment by krancour** [comment]
@stavalfi, to clarify one thing, the core of Brigade is pretty well decoupled from the gateways. The API you referenced at https://docs.brigade.sh/intro/quickstart/#send-a-simpleevent-to-the-generic-gateway is an API for the _generic gateway_; not for Brigade itself.
