### ISSUE TITLE
Wrong genericGatewaySecret when using generic gateway

### ISSUE THREAD

**Issue by stavalfi** [brigadecore/brigade#1129]
hi guys :wink:

I’m not sure how to get this to work: https://docs.brigade.sh/intro/quickstart/#send-a-simpleevent-to-the-generic-gateway

```
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{
    "key1": "value1",
    "key2": "value2"
}' \
  http://localhost:8081/simpleevents/v1/brigade-4897c99315be5d2a2403ea33bdcb24f8116dc69613d5917d879d5f/KUNEmtCaiKYwRyR6sMuXIX7J
```
`KUNEmtCaiKYwRyR6sMuXIX7J` is what I defined when I setup my project but I get an error: secret for this Brigade Project is empty, refusing to serve, please inform your Brigade admin .
to check it, I run `kubectl edit secret brigade-ad69a7a3ee34cd22990635152bdfd98fe540c90e9d885353a332c3`
and I see:  `genericGatewaySecret: ""`

project configuration:

```
 p/nc {stav/break-to-modules} $ brig project create
? VCS or no-VCS project? VCS
? Project Name stavalfi/nc
? Full repository name github.com/stavalfi/nc
? Clone URL (https://github.com/your/repo.git) https://github.com/stavalfi/nc.git
? Add secrets? No
? Where should the project's shared secret come from? Auto-generate one now
Auto-generated a Shared Secret: "KUNEmtCaiKYwRyR6sMuXIX7J"
? Configure GitHub Access? Yes
? OAuth2 token .....................
? GitHub Enterprise URL
? GitHub Enterprise upload URL
? Configure advanced options No
Project ID: brigade-ad69a7a3ee34cd22990635152bdfd98fe540c90e9d885353a332c3
```

What is the problem?

* I tried to re-create the project with custom `Shared Secret` as well and I got the same error.

----------------

Output of `brig version`:

`v1.4.0`

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

```
minikube version: v1.12.3
commit: 2243b4b97c131e3244c5f014faedca0d846599f5
```

**Comment by krancour** [comment]
@stavalfi, it's admittedly a bit confusing...

The `Auto-generated a Shared Secret: "KUNEmtCaiKYwRyR6sMuXIX7J` is talking about a secret that can be shared between a GitHub app (like the GitHub event gateway) and the project. It doesn't have anything to do with the generic gateway that you're trying to use.

To configure the shared secret for the _generic gateway_, you need to answer `Y` to `Configure advanced options` and it's the last in quite a long series of options.

fwiw, Brigade was always meant to be as loosely coupled as possible to gateways and we regret that gateway-specific details such as these shared secrets have bled into Brigade's core, resulting in Brigade itself having a somewhat tighter coupling to those particular gateways. Unfortunately, we can't undo that tighter-than-desired coupling without some breaking changes... but...

The confusion you've just experienced will go away in 2.0, however, because we're doing a much better job there of decoupling Brigade's core from the gateways. In cases like these where the GitHub gateway or generic gateway need to agree with their own upstream clients on a shared secret, that's a matter of configuration when deploying the gateways and _not_ anything that Brigade itself needs to be concerned with. In turn, that will make project creation less onerous for users-- and in fact, we're abandoning the tedious, interactive process in favor of project definitions that look more similar to Kubernetes manifests-- and we'll even have JSON schema so your editor can offer you context help as you write such a project definition.

**Comment by stavalfi** [comment]
thank you!
