### ISSUE TITLE
Git Initializer: Unit/Functional Tests

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1230]
We should add low-level tests that vet the git initializer go binary directly, ideally written in go for parity.  The only reason I'm hesitating to call them unit is they may require standing up a minimal git server to interact with, as was done in the [v1 version of this component](https://github.com/brigadecore/brigade/blob/master/git-sidecar/test/test.sh).  But by all means, the lower the level the better for this particular issue.

We can use those v1 tests as a basic guide for minimal scenarios to cover.  Here's a snippet, where the first value is supplied as the ref (or commit) to the binary and the second value is the expected value of `git rev-parse --short FETCH_HEAD` (or similar) after checkout.

```
echo ":: Checkout tag"
test_clone "v0.1.0" "ddff78a"
echo

echo ":: Checkout branch"
test_clone "hotfix" "589e150"
echo

echo ":: Checkout pull request by reference"
test_clone "refs/pull/1/head" "5c4bc10"
echo

echo ":: Checkout sha"
test_clone "589e15029e1e44dee48de4800daf1f78e64287c0" "589e150"
echo
```

Follow-up from https://github.com/brigadecore/brigade/pull/1229

**Comment by krancour** [comment]
Throwing this out there-- I don't (personally) care if a test tossed in with the unit tests isn't a unit test in the truest sense.

Maybe instead of standing up our own minimal git server, we can test against a repo we own in github. GitHub's pretty much always up. We have repos there (like this one) that we know will exist indefinitely. If GitHub's down or this repo isn't available, we already have bigger problems than not being able to run _these_ tests. We wouldn't be able to run _any_ tests. 😉 

i.e. A dependencies GitHub and a specific repo therein that we own seem like fairly safe things to take for granted.

I'm not saying we can't or shouldn't _eventually_ stand up a minimal git server to facilitate these tests, but this approach would get us more coverage faster.

**Comment by krancour** [comment]
@vdice did #1229 take care of this issue?

**Comment by vdice** [comment]
@krancour Indeed, I think we can close this as we're currently pretty happy with the test coverage added in 1229.  We can always re-open or revisit as the need arises.
