### ISSUE TITLE
brig event list should provide limit and non-interactive options

### ISSUE THREAD

**Issue by itowlson** [brigadecore/brigade#1328]
Currently `brig event list` displays the first 10 (I think) events and then prompts with `<n> results remain. Fetch more?`  This causes a couple of problems:

1. If I only want to see the most recent event(s), I have to hit `No` every time I run the query
2. I can't easily write scripts to process events

(The interactive paging, by the way, is particularly odd with `-o json` where it prints a 10-item `EventList` object, then prompts and if you choose Y prints another `EventList`.  I assume `-o json` is really intended to work only with redirects.)

The interactive prompt doesn't display if the output is redirected, so you can work around the prompt by writing `brig event list | cat`.  Or you could write `brig event list | head -n 3` to print the first event (3 because 1 blank line and 1 header row).  But it would be good to have a built-in option that could limit the number of results and/or suppress the prompt.

**Comment by krancour** [comment]
A lot going on in this issue...

> If I only want to see the most recent event(s), I have to hit `No` every time I run the query

I had considered making "No" the default initially, but decided that accidentally accepting a default "Yes" would be less inconvenient for someone who _didn't_ want more than accidentally accepting a default "No" would be for someone who was already 20 pages deep and would then have to start all over again to get to page 21.

imho, the default should remain "Yes."

> I can't easily write scripts to process events

> The interactive prompt doesn't display if the output is redirected...

More precisely, the interactive prompt isn't displayed when there isn't a tty. idk where my head was that day, but I must have been operating under the assumption that scripts won't have a tty-- which is absolutely _not_ a given.

_So, for sure, something more can be done on this front._

> The interactive paging, by the way, is particularly odd with `-o json` where it prints a 10-item `EventList` object, then prompts and if you choose Y prints another `EventList`.

I'm unclear as to what's odd about that. Could I ask you to elaborate?

> Or you could write `brig event list | head -n 3`

That is in fact what I do personally. I believe other tools have conditioned me into impulsively piping into `head` and that may have caused me to take that for granted as "normal." 

> But it would be good to have a built-in option that could limit the number of results and/or suppress the prompt.

I agree in principle, but I'm not at all clear on what this would look like. I've outlined some possibilities below.

## Possibility 1: A `--limit` flag

There are basically two implementations of a `--limit` flag we could consider and they're both problematic.

### 1A: Retrieve one giant page

This is problematic because `--limit 100000` could get us into big trouble with OOMs either client side or server side. (This is why the results are pageable to begin with.)

We could address that by setting some TBD ceiling on the value of `--limit`. That would therefore be useful for use cases where you want a modest number of results and don't want to be bothered by interactive prompts, but it would _not_ be useful for use cases that want a larger number of results.

But it should be noted that this isn't really any better than what you already get by piping the results into `head`. So would it be worth it? imho, I wouldn't bother.

### 1B: Retrieve many smaller pages and stitch the results together

Still problematic because whether we're talking about a formatted table or a JSON object, we'd be manipulating a potentially very large object in memory and would therefore still run the risk of a client-side OOM.

We could address that if we were willing to accept "page breaks." i.e. Instead of actually stitching results together, we'd output a single page of results at a time as they are retrieved. For `-o table`, this is multiple tables where the columns in one won't line up precisely with the columns in the next. For `-o json` this means multiple distinct JSON objects output to stdout instead of just one. To say the least, that would be weird and difficult to _parse_, which inclines me toward not bothering with this approach either.

## Possibility 2: A `--non-interactive` flag

For `-o table`, allow `--non-interactive` to suppresses the interactive prompt (even if there's a tty), and replace it with a message that states how many results remain.

For `-o json` or `-o yaml`, allow `--non-interactive` to suppresses the interactive prompt (even if there's a tty). Don't replace it with anything. Information about how many results remain is already contained _in_ the JSON or YMAL.

The problem with this is that with the `--non-interactive` flag set, there's no way to get to the second page or beyond, unless we combine it with...

## Possibility 3: Expose `continue` directly as a flag

The way paging works in the API uses a scheme borrowed from Kubernetes. When you get more than n results (20 by default), the response you get back tells you how many results remain and _also_ contains a "continue" value that is _opaque_ from the client's perspective and understood only by the API server. You blindly send it _back_ to the server in your "next page" API call. It gives the server the info it needs to fast forward past the results it already gave you.

Currently, when you answer "Yes" to the interactive paging prompt, the CLI is just adding the `continue` value from the current page to the `continue` query param for the next page _for you_.

We could expose this query parameter as a `--continue` flag.

With possibility no. 2 above, when you `brig event-list -o json --non-interactive`, you get the first page only and no interactive prompt. With `-o json` or `-o yaml` the correct continue value for you to use in your next call is embedded in the response already. Your next command can be `brig event-list --non-interactive --continue <continue value from previous page>`.

For `-o table`, besides suppressing the interactive prompt and replacing it with a message that states how many results remain (as described by possibility no. 2 above) the correct value to furnish to the `--continue` flag in your next command could also be displayed.  Your next command could be `brig event-list -o table --non-interactive`. I don't see this as very user friendly, but realistically, a _human_ user who wants to page is going to do it interactively, anyway, so any user unfriendliness is largely moot in this case.

## Summary

My vote is:

* A combination of no.2 and no.3 allows scripts to intelligently iterate over pages of results. Humans are unlikely to use these features.

* Humans wanting _fewer_ than a page worth's of results can continue to pipe results into `head`.

_I'm also open to other suggestions._

Lastly, not for nothing, we have an API. Scripts that surpass some arbitrary level of complexity really might want to consider using the API directly instead of using the CLI as a programmatic interface, which it is not.

**Comment by itowlson** [comment]
@krancour Re JSON output being multiple objects:

> I'm unclear as to what's odd about that. Could I ask you to elaborate?

I'm not sure what a sensible behaviour is, to be honest.  You clearly can't just stop halfway through a JSON object - that would no longer be valid JSON.  But I cannot imagine what I could usefully do with multiple lists.

Maybe it's irrelevant because JSON would always be redirected (to a file or to `jq` or something) so you would never see the prompt in real world use cases.

**Comment by krancour** [comment]
I think we're on the same page?

I think if you're using the CLI as a programmatic interface, which again, I don't encourage past some certain degree of complexity, you need to accept that your script needs to have a loop for retrievimg multiple pages.

I'll make sure the righy flags exist to make that possible.

**Comment by krancour** [comment]
Closed by #1334
