### ISSUE TITLE
Add yarn audit job

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1439]
We should add a job to our brigade.js to run `yarn audit`.

GitHub automatically scans for npm dependencies with known vulnerabilities, but it only seems to do this for master/main branches.

I'd like to get these same checks happening on our `v2` development branch on a regular basis.

**Comment by krancour** [comment]
@willie-yao this might be a good quick/easy thing for you to work on. @vdice can almost certainly help you with `Makefile` and `brigade.js` (for Brigade 1.x) if you get stuck.

**Comment by radu-matei** [comment]
@willie-yao - let me know if you need any help or guidance on this, I can also pick it up if you are working on other things.

**Comment by willie-yao** [comment]
Awesome thanks. I've been working on the init feature, but I can take a look at this tomorrow and let you know how that goes!

**Comment by radu-matei** [comment]
There two ways in which this could be implemented:

- the first, and easiest, would be to append `yarn audit` to an existing JS-related `make` target that is already executed, for example `make lint-js`. This has the advantage of not modifying anything other than the `Makefile`, but the output and the job's result is going to be put together with the linting result (and I don't think we really want this, since in the end they look different enough that they should be different jobs).

- the other one is to add a new `make` target specifically for `yarn audit` (for example, see how the target for linting is defined - https://github.com/brigadecore/brigade/blob/5debb10f3d08728a30c98746ac4cba5319bc29ea/Makefile#L132-L144), then create a new job for the audit in `brigade.js` (see how the linting job is defined and appended to the jobs array - https://github.com/brigadecore/brigade/blob/v2/brigade.js#L69-L73), then actually run it as a result of a new git event (https://github.com/brigadecore/brigade/blob/v2/brigade.js#L260).

cc @vdice in case I missed any steps in there.

**Comment by willie-yao** [comment]
Created a pull request [here](https://github.com/brigadecore/brigade/pull/1443) with the yarn audit job added. Let me know if everything looks good!
