### ISSUE TITLE
Worker resource cleanup if/when a worker pod manually deleted

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1506]
When a worker pod is manually deleted, will all associated K8s resources be successfully cleaned up?  @krancour thinks there may be some hardening we can do here.

**Comment by krancour** [comment]
1. This is the observer code that is called whenever the observer sees a worker pod has been created or updated. At the very end, it initiates cleanup if the pod is in a terminal state.

    https://github.com/brigadecore/brigade/blob/v2/v2/observer/workers.go#L46-L133

    This cleanup process starts a 60 second grace period to allow the log aggregator to catch up if it needs to, then uses the API server to _complete_ cleanup, which will delete _all_ k8s resources associated with the worker.

2. At that point there is _separate_ code that is invoked when the observer sees a worker pod that has been deleted:

    https://github.com/brigadecore/brigade/blob/v2/v2/observer/common.go#L13-L22

The thing that could _potentially_ happen when a worker pod is deleted manually is that part 1 doesn't occur, but part 2 does.

I say _potentially_ because I'm not sure what k8s actually _does_ when a pod is deleted. Does it terminate it _first_ and _then_ delete it. i.e. Is there a detectable state change that occurs prior to the deletion? If so, then our bases are covered.

I will research this and experiment a bit to see what actually happens.

**Comment by krancour** [comment]
I have just confirmed through experimentation that cleanup does not occur when a worker pod is deleted manually.

I'll get this straightened out.
