### ISSUE TITLE
discussion: include gateway docs

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1535]
Current v2 docs just link to each gateway's own README.md.

Do we want to include more polished gateway docs directly in the Brigade docs?

**Comment by vdice** [comment]
We do have a holdover/placeholder Gateways topic doc: https://github.com/brigadecore/brigade/blob/v2/docs/content/topics/operators/gateways.md

This still needs to be revised/updated for v2.

See also https://github.com/brigadecore/brigade/issues/1508

**Comment by krancour** [comment]
@vdice one thought I've had about this...

Could we / should we have _generic_ gateway docs? (To disambiguate: Not the "generic gateway," but docs that are generically applicable to all gateways?) And then leave the specifics to each gateway's own documentation?

**Comment by vdice** [comment]
@krancour I forgot this issue was still around.  We do now have an overview doc on Gateways with a sample written in Go, added in https://github.com/brigadecore/brigade/pull/1569.  The doc can be seen here: https://v2--brigade-docs.netlify.app/topics/operators/gateways/

Meanwhile, you've done a great job of adding docs on each of the gateways in this brigadecore org, so I'm thinking we're good to close this one out -- unless there were some other facets we'd like to cover?

**Comment by krancour** [comment]
@vdice I think everything is covered.
