### ISSUE TITLE
Kubernetes Service Account permissions of Pod from Job

### ISSUE THREAD

**Issue by jacobbraaten** [brigadecore/brigade#1650]
I have question regarding using a Container Image that uses kubectl as one of the containers that a Job runs in. 

I've gotten the project created and running inside of the kubernetes cluster. The issue I am running into is that the service account the pod runs as does not have the correct permissions to actually perform the command I am trying to run. 

Finally to the question, is there a way that I can give more permissions to the Service Account that is executing the Pod? Is this documented somewhere that I missed or is this currently not an option? 

project.yaml for reference
```
apiVersion: brigade.sh/v2-beta
kind: Project
metadata:
  id: first-project
description: My new Brigade project
spec:
  eventSubscriptions:
  - source: brigade.sh/cli
    types:
    - exec
  workerTemplate:
    logLevel: DEBUG
    defaultConfigFiles:
      brigade.ts: |
        import { events, Job } from "@brigadecore/brigadier"
        
        events.on("brigade.sh/cli", "exec", async event => {
        	let job = new Job("hello", "bitnami/kubectl:1.19.15", event)
         	job.primaryContainer.command = ["kubectl"]
         	job.primaryContainer.arguments = ["get", "po", "--all-namespaces"]
         	await job.run()
        })
        
        events.process()
```

**Comment by vdice** [comment]
Hi @jacobbraaten, thank you for this issue.  Definitely an interesting one.  You are correct: currently there isn't a way to specify custom rbac policy/rules for either the worker or job pod(s).  As of writing, the roles for both the worker and jobs have empty policy rules; in other words, no real abilities to access resources in any fashion. @krancour to check my understanding here.

This area is certainly ripe for discussion.  Would we want worker/job pods to be able to access resources globally in the K8s cluster they are running in -- and/or allow freeform policy config?  Definitely security considerations here, especially when dealing with jobs that have the potential to use any Docker image out there, etc.  Or, do we consider allowing for arbitrary policy but _only_ within the project namespace that the worker/jobs belong?

Well, let me stop speculating and give you a chance to describe your use case(s), if willing, and then we can go from there.  Thanks!

**Comment by jacobbraaten** [comment]
Hi @vdice I agree there are a lot of considerations in regards to this implementation. 

The use case I was imagining is as follows. The team I work on is responsible for deploying and managing our companies kubernetes platforms and with that comes monitoring and alerting. Some of these alerts can be fixed by known processes that currently require an engineer to manually do. 

With the right set of tooling it would be possible to automate this. I liked the idea of using Brigade for that as it would only allow for the fixes to be applied to the cluster in error and would remove the concern of how to know where to send the alert since the alert already knows what cluster it belongs to.

**Comment by krancour** [comment]
Hey @jacobbraaten. Sorry for the delay responding. I was off for a few days.

You're definitely bumping up against the edges of Brigade's k8s abstraction right now. As @vdice noted, we don't have a way of configuring RBAC rules-- and there isn't currently any plan to add that either. I'll give you some background, but don't worry... I think this response has a happy ending.

With Brigade 1.x, it was a frequent complaint among users that they too often had to "drop down to Kubernetes" to get things done. This made k8s knowledge, _direct_ access to a cluster, and a not-so-modest set of permissions an unfortunate pre-requisite for implementing even simple uses cases-- use cases for which the extent of k8s' role is to _run_ the workloads. Use cases that programmatically _interact_ with the k8s cluster have been comparatively uncommon.

With v2, we set out to make Brigade more useful to users who don't know much about k8s, lack direct access to a cluster, or simply wish to work at a higher level of abstraction. Our goal was to go "80/20" and make sure our abstraction covered those common cases well, _without_ users needing to "drop down to Kubernetes."

Given the existence of that abstraction, we cannot assume that all Brigade users have direct access to the underlying cluster. Even in cases where one does, since Kubernetes doesn't offer any way for us to federate Brigade users with cluster users, Brigade doesn't have any way of knowing what a given user is and is not authorized to do within the cluster-- in fact it has no way of knowing whether a given user is authorized to access the cluster _at all_. This being the case and in the interest of Brigade not becoming an avenue to gain or elevate permissions within the cluster, Brigade's k8s abstraction ends here.

_However_, for users who wish to interact programmatically with the cluster, rather than leave them high and dry, we tried our best to not interfere and to the extent possible, make their life a little bit easier. So, while Brigade does not abstract RBAC roles and bindings, it _does_ do the following:

* Every project is auto-assigned a unique namespace. You can determine a project's namespace by retrieving a YAML or JSON representation of the project. (Example: `brig project get -i hello-world -o yaml`)

* Within that namespace are two service accounts (one for the worker; one for any jobs created by the worker). Similarly, there are two (empty) RBAC roles (again; one each of the worker and jobs), and two role bindings (to associate the aforementioned service accounts with the aforementioned roles).

* Every worker spawned by Brigade (for a given project) uses the aforementioned worker service account. Every job spawned by Brigade (again, for a given project) uses the aforementioned job service account.

Users having 1. the need to do so, 2. direct access to the cluster, and 3. adequate permissions to do so, can directly modify the RBAC roles in their project's namespace. With all the other dots already connected by Brigade, this should be all that is required to get worker and/or job pods interacting programmatically with your cluster.

I hope this is in some way helpful. lmk!

**Comment by jacobbraaten** [comment]
@krancour all of that makes a lot of sense with the design decisions you all have made. 

I didn't notice the RBAC stuff for the individual projects. That should allow the PoC to continue forward. 

Thanks for the help.

**Comment by krancour** [comment]
@jacobbraaten my pleasure. We appreciate everyone who's kicking the tires on v2 right now, so please don't be shy about reaching out as your PoC continues!
