### ISSUE TITLE
General way to marking a hook as trusted/untrusted

### ISSUE THREAD

**Issue by bacongobbler** [brigadecore/brigade#22]
<a href="https://github.com/technosophos"><img src="https://avatars1.githubusercontent.com/u/89193?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [technosophos](https://github.com/technosophos)**
_2017-10-10 19:20:19_

----

We need a way of marking whether a hook is untrusted and should not have access to a Project's secrets.

For example, one might want to mark `github` `pull_request` as untrusted, and thus not allow an acid.js to access secrets.

/cc @krancour

**Comment by bacongobbler** [comment]
**Comment by [technosophos](https://github.com/technosophos)**
_2017-10-10 20:58:59_

----

I would strongly prefer that this is a configurable thing via the Project.

**Comment by technosophos** [comment]
We implemented a specific fix for the GitHub gateway. Might still be a way to do a general fix.

**Comment by technosophos** [comment]
So I think the general design of this would be to add an attribute on the event that was something like `trusted: false`. The Worker's `index.ts` would then wipe out the `project.secrets`.

But the problem is that the worker can still manually load the project and bypass the taint. So really this doesn't get us much more than a band-aid.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
