### ISSUE TITLE
Feature: Add Project functionality to bring in brigade.js from another location

### ISSUE THREAD

**Issue by squillace** [brigadecore/brigade#272]
Use case: organizations who choose to keep CI/CD/Automation environment information in the hands of specialized teams to enable greater agility for development and ops would like the brigade pipeline .js file pulled from somewhere they can control, using the same ci/cd/automation methods that brigade implements for applications.

Discussion: Whilst I love having the brigade project **with** the code for many scenarios, _in particular_ those in which the developer wears many hats, organizations will begin to specialize, focusing in on operations vs. development, and so on. This remains true whether they're doing very agile work or not. 

In these cases, I would like to see the ability to specify a line in the project yaml, something like:

```
brigadeScriptRepo: <repo URL>
brigadeScriptRepoSecrets:
- username: 
- password: 
```

or whatever is deemed appropriate such that, when the triggering event is received, the brigade project can retrieve the brigade.js file to execute from the (potentially private) repository, and CI/CD information is in this case not stored with the code. 

I note that this seems like it makes brigade more flexible, but at the same time maintain the default assumption that, absent this information, the current behavior would continue.

**Comment by technosophos** [comment]
Since it is the vcs-sidecar that gets the brigade.js in some situations, we can also explore if there is an easy way to have the sidecar fetch the file from another repo.

**Comment by germanjrd** [comment]
I would like to use brigade to run enterprise batch jobs, but pulling the script from a git repo would force us to treat our git deployment as a secure, enterprise, highly-available application, with more restrictions than what is typically required for a source code repository, I would like for brigade to be able to read the scripts from an S3 resource or a data store for example.

**Comment by technosophos** [comment]
All you need to do @germanjrd, is replace the git-sidecar with a Docker image that pulls your data from your preferred location and puts it in the right location. The sidecar is configurable in the project settings (`vcsSidecar: someImage:tag`).

I wrote an example app a while back that mounted the file system of my working image instead of using a Git checkout. Here's where I changed the vcs sidecar: https://github.com/technosophos/node-demo/blob/master/example-values.yaml#L19

And the Dockerfile ran a script that did this:

```
cp /app/brigade.js $BRIGADE_WORKSPACE/brigade.js
```
(https://github.com/technosophos/node-demo/blob/master/start.sh)

So I would imagine that all you'd need to do is grab an existing Docker image that has an s3 client, and then write a simple script to grab what you want and drop it into `$BRIGADE_WORKSPACE/whatever`.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
