### ISSUE TITLE
Use GH issue_comment events to trigger builds

### ISSUE THREAD

**Issue by tiriplicamihai** [brigadecore/brigade#484]
First of all, I've just discovered brigade and it's awesome!
I checked the code and noticed that builds can't be triggered by an `issue_comment` event. I'm thinking about something like "Trigger Phrase" from Jenkins. I think this functionality helps because there are cases when you push frequently but you want to control when the build gets triggered (a reason could be that the build takes a long time). 

What are your thoughts on this? If you find it useful I can look into it, propose a solution and then implement it.

**Comment by mumoshu** [comment]
@tiriplicamihai Hi, thanks for your interest on the project 👍 

I believe that your use-case of triggering a brigade event from `issue_comment` would be super useful.
I was using  a gh `deployment` event to trigger a deployment brig pipeline and it worked very well. Probably `issue_comment` events would be a more general solution to manual triggers.

Regarding the implementation, you can add a case for `github.IssueCommentEvent` [here](https://github.com/Azure/brigade/blob/master/pkg/webhook/github.go#L89).

Probably we have no way to populate `rev.Commit` because a `issue_comment` event won't have a commit sha1 in it. How about just omitting it?

`rev.Ref` is another concern. It is used to load `brigade.js` which contains all the brigade event handlers and pipelines. Perhaps you have two options, `master`, or `refs/pull/$pr_number/head` if you're focusing on pull requests.

Please feel free to ask me anything about the implementation. I'm happy to help!

**Comment by tiriplicamihai** [comment]
@mumoshu Thanks! I'll look into it in the next few days and hopefully I will have a PR ready for review.

**Comment by tiriplicamihai** [comment]
@mumoshu I got something done but I did hit a small blocker - where should be the check for the trigger phrase be?
At first, I thought about letting the developers check them in `brigade.js` but thinking more about it, I'm not sure it's ok to start builds and then check the condition.
The other option would be to set it in the project (via values.yml) and check the phrase there.
What do you think about this?

**Comment by ovidiubute** [comment]
Isn't the responsibility of checking whether or not to trigger a new job up to the Gateway? To me this is the same problem as trying to schedule a build once a day. You could either keep creating new builds and check that the time is right inside the job, which would be extremely inefficient, or you could implement a specialized cron gateway that doesn't start the jobs until the time is right.

**Comment by vdice** [comment]
We've put up an implementation that should cover this feature request in https://github.com/brigadecore/brigade-github-app/pull/56 .  (Note that since this issue was created, the 'classic'/GitHub gateway has been removed from brigade itself -- it now lives at https://github.com/brigadecore/github-gateway-oauth.  The implementation has been added to the newer, suggested default of the GitHub App-based gateway.)

**Comment by vdice** [comment]
Going to consider this feature completed with https://github.com/brigadecore/brigade-github-app/pull/56.  Closing.
