### ISSUE TITLE
Generic Webhook Handler

### ISSUE THREAD

**Issue by technosophos** [brigadecore/brigade#602]
Per the 1.0.0 feature list:

- Add a generic webhook gateway to the API server (`POST /webook/:projectID/:secret`)
- Make this webhook callback configurable: It should be possible to disable this from config
- Add support in the charts/brigade chart (to turn of webhook gateway)

The gateway should create an event named `webhook`, and the payload should be whatever data was posted.

For `:secret`, we need to generate a per-project secret that can be embedded in the URL and validated per request. This prevents someone from finding all the projects and just spamming these projects with requests.

**Comment by technosophos** [comment]
It should be disabled by default, and the main documentation should include enabling it:

```
$ helm install brigade/brigade --set generic-gateway=true
```

**Comment by dgkanatsios** [comment]
Started a PoC for this on my local fork [here](https://github.com/dgkanatsios/brigade/commit/afb4c3466d50d13e23352231c5d5e0c8367128dd), looking for review

Points:
- what would the Generic Webhook payload? Currently I'm using 
```json
{
	"ref":"master",
	"commit": "lolo"
}
```
Is it enough?
- missing tests
- missing chart configuration (need to deep dive into charts' creation, pretty n00b)
- feeling a bit weird about [this](https://github.com/dgkanatsios/brigade/commit/afb4c3466d50d13e23352231c5d5e0c8367128dd#diff-eb4368b2ea4c9fce4a0dbedd95b4fbba). Explain: all source code files in the 'webhook' folder use Gin, whereas I used go-restful, since all the other methods on API server use that. Thoughts?
- added a new [field](https://github.com/dgkanatsios/brigade/commit/afb4c3466d50d13e23352231c5d5e0c8367128dd#diff-31af9081d3895845fef9878bdabf43dd) on Project struct with the GenericWebhook secret which can be [auto-generated](https://github.com/dgkanatsios/brigade/commit/afb4c3466d50d13e23352231c5d5e0c8367128dd#diff-f6bea21b11d01f1d30a6d06a42dfbd70)
- not sure about [this](https://github.com/dgkanatsios/brigade/commit/afb4c3466d50d13e23352231c5d5e0c8367128dd#diff-e85de98a3a4e38132ded5611895551c3R180) configuration

Thank you!

**Comment by vdice** [comment]
@dgkanatsios the PoC looks great to me.  Let me know when I can help test and perhaps later next week @technosophos and others can take a look (hectic conference schedule currently!)

**Comment by dgkanatsios** [comment]
Thanks for the review! I’m off as well, will resume mid next week and let you know :)

**Comment by dgkanatsios** [comment]
PR created [here](https://github.com/Azure/brigade/pull/721)

**Comment by dgkanatsios** [comment]
As [discussed](https://github.com/Azure/brigade/pull/762#issuecomment-454799925), Generic Webhook is now a separate component
