### ISSUE TITLE
Provide ARM images

### ISSUE THREAD

**Issue by Alxandr** [brigadecore/brigade#773]
I would like to run brigade on my cluster running on arm64 nodes. Looking at the makefile, it seems that the project is made to support building for multiple architectures, would it be possible to release images for arm64 as well?

**Comment by radu-matei** [comment]
Hi, @Alxandr, thanks for opening the issue!
A couple of things first:

- would the entire cluster be ARM-based? More specifically, Brigade has a control plane (controller + API and a front-end) and the worker, which starts job pods. Are all the components going to run on ARM nodes?

- I think we can build ARM images (through [Azure Container Registry Build/Tasks](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/container-registry/container-registry-tasks-overview.md#what-is-acr-tasks)), and Helm has an ARM release (for Tiller), so unless I'm missing something, we should be good to go.

- as I don't have an ARM cluster handy at the moment (and I don't think it would be that easy to provision one), would you be able / willing to help us with the testing?

Thanks!

**Comment by Alxandr** [comment]
My entire cluster is based on ARM nodes. I have 3 nodes, all running arm64. I already have tiller running on it, but I've yet to find a single tiller app that I can install 😛 , and I could definitely help with testing. That being said, it's also possible to build/test without running on actual arm nodes. I build an image for the unifi controller using qemu inside the images here: https://github.com/Alxandr/unifi-controller/blob/master/build.sh. Docker seems to have some built in support for it. That being said, I'm no expert on docker, nor kubernetes so this might not be the best way of going about it.

Anyways, I would gladly test things. Currently however, my cluster is a bit limited with 1 node with a total of 4GB of ram, because there was an issue with the power supply I was going to use for the other nodes, so I will have to get that fixed before I can run anything that takes more ram.

**Comment by Alxandr** [comment]
Then by all means, I can test things. I do probably need some instructions though.

**Comment by radu-matei** [comment]
Absolutely!
When we open the PR that adds the images, there will also be instructions on how to test it.

Thanks!

**Comment by radu-matei** [comment]
- first of all, we need to build all of our binaries for ARM. For the Go projects, here is a [resource explaining how to cross-compile for various ARM versions](https://github.com/golang/go/wiki/GoArm).
We would then add a new target to the Makefile, `build-arm-bins`, for example, similar to [the existing `build-docker-bins`](https://github.com/Azure/brigade/blob/master/Makefile#L42), which would build the binary for the component, then build the Docker image.

- the thing I am not familiar with is what version / specific architecture for ARM are most popular. Assuming `arm64` (is that compatible with a Raspberry Pi, for example?), then we need a new Dockerfile for each project (`Dockerfile.arm`, for example). For the Go projects, because we have static compilation, we will have a minimal Dockerfile, starting from an Alpine ARM base image ([here is a list of maintained Alpine ARM images](https://hub.docker.com/r/arm64v8/alpine/)). Here is an example for the Brigade API:

```
FROM <this would be alpine arm64>

RUN apk add --no-cache ca-certificates && update-ca-certificates

COPY rootfs/brigade-api /usr/bin/brigade-api

CMD /usr/bin/brigade-api
```

This is how all Dockerfiles for ARM of Go components would look like.

- now for the Brigade worker, which is a NodeJS project - similarly, we need to start from an [ARM Alpine Node base image](https://hub.docker.com/r/arm64v8/node/) and use [the existing Dockerfile of the worker for reference.](https://github.com/Azure/brigade/blob/master/brigade-worker/Dockerfile)
This raises the interesting question of duplicating the Dockerfiles - would it make sense to contain in scripts the things we do in the Dockerfiles? Surely, I don't think it's necessary for the first iteration, but it would be nice to keep in mind (cc @vdice).

- make sure to add the correct tags for the ARM images. 

Is it a bit more clear?

After we have this working it would be really cool to look at multi-architecture Docker images. Resources [here](https://blog.docker.com/2017/11/multi-arch-all-the-things/) and [here](https://medium.com/@mauridb/docker-multi-architecture-images-365a44c26be6) - this way, we only provide the tags and a manifest list, and each Docker engine pulls its supported version of the image.

Let us know if you have any questions, we're glad to help.
Thanks!

**Comment by radu-matei** [comment]
Hi, @Alxandr!
Did you have a chance to look over the steps needed for this? Is there anything we can help with at this point?

Thanks!

**Comment by Alxandr** [comment]
Yeah. Sorry, I got stuck in setting up backup of the cluster (let's just say brigade isn't the only thing not providing ARM images 😛 ). I have that part solved though, so I will probably be moving on to brigade later today (or this weekend).

**Comment by Alxandr** [comment]
I've update the makefile to produce arm64 images. I've yet to test them though. Need to figure out how to do that best.

**Comment by radu-matei** [comment]
That seems like a great start!
Feel free to open a work in progress pull request, so we can track all the work there and discuss any questions about the implementation along the way.
