### ISSUE TITLE
Docs/CI: Ability to preview generated docs sites for PRs

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#839]
The [docs makeover](https://github.com/Azure/brigade/pull/814) by @flynnduism is so nice.  Just check out https://docs.brigade.sh !

I'm curious if we'd be able to add a CI step to preview/check rendered docs from PR branches?  For instance, on a recent PR, we weren't entirely sure how to be certain that doc pathing updates will render appropriately; see https://github.com/Azure/brigade/pull/831#discussion_r264570469

**Comment by flynnduism** [comment]
@vdice by default Netlify will do this with new PRs, **but** first we have to resolve a GitHub permissions issue. Currently Netlify isn't approved for this `github.com/Azure/brigade` repo. I've sent an app request.

![Screen Shot 2019-03-12 at 10 47 38 AM](https://user-images.githubusercontent.com/686194/54223276-61f8ad00-44b4-11e9-9d0f-262de8d5e88f.png)

Until it can get proper access to `master` there, I've pointed it at fork - `flynnduism/brigade`, which is why currently PRs are not building - the proper repo is not being watched for webhook events. Hope to get this resolved today.

**Comment by flynnduism** [comment]
Ok, the benevolent @michelleN added me to repo admins, and I can see that Netlify access is not granted there. I gotta check with Azure admins...

@vdice do you have any pointers on this? I'm assuming you had to follow a similar process for the `deislabs-ci` config...

![Screen Shot 2019-03-12 at 11 01 44 AM](https://user-images.githubusercontent.com/686194/54224371-9f5e3a00-44b6-11e9-896b-2922fe749124.png)

**Comment by vdice** [comment]
Netlify has been added and appears to be working great!  Thanks again @flynnduism !
