### ISSUE TITLE
End to end testing for Brigade

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade#879]
I think it's time we started end-to-end tests for Brigade. To achieve this, we first need to build and push container images for Brigade components for all pull requests (#761).

Then, I think we have the following approaches we could take:

- we can deploy Brigade in a new namespace, following [this really cool article on how to create preview environments with Brigade](https://medium.com/devopslinks/development-in-the-cloud-4aa2cabd3880). I think this would be the most straightforward and fastest way to run the tests, since the Kubernetes cluster would already be provisioned and running. However, the tests would be restricted to the Kubernetes version running on our Brigade instance.

- use `kind` to create a cluster and configure Brigade. This has the advantage of allowing us to easily test against multiple Kubernetes versions (at least whatever versions `kind` supports), but the disadvantage of not running in a real-world environment.

- create a fully fledged cloud-provided Kubernetes cluster (AKS/EKS/GKE), then deploy Brigade (optionally, we could do this using CNAB). For this, we would need knowledge and credits for various cloud platforms (we already have these for AKS).

Then, once we have a cluster / namespace and a Brigade instance, we can define some projects and run jobs.

Thoughts?

**Comment by dgkanatsios** [comment]
I've been playing a bit with [kind](https://github.com/kubernetes-sigs/kind) and I really like it.
[Here's](https://github.com/dgkanatsios/azuregameserversscalingkubernetes/tree/master/e2e) what I've been doing with my project. Steps:

- use the [run.sh](https://github.com/dgkanatsios/azuregameserversscalingkubernetes/blob/master/e2e/run.sh) to `kubectl create` my Deployments. Similarly, we could use this to `helm install Brigade`
- wait till these Deployments are up and running with [this](https://github.com/dgkanatsios/azuregameserversscalingkubernetes/blob/master/e2e/wait-for-deployment.sh) script
- then, I do have [this](https://github.com/dgkanatsios/azuregameserversscalingkubernetes/tree/master/e2e/cmd) app that basically creates stuff in Kubernetes and then waits (well, polls) till they are up and running and reports accordingly. We could use a similar app to
   - create a bunch of Projects (by creating Secrets). 
   - Trigger some Builds on them and wait for the expected outcome
   - we could probably test Generic/GitHub Gateway as well by issuing expected HTTP requests and wait for the expected outcome

In any case, if we go down this way (since I think that this is huge), we should begin with a simple skeleton and then built on top of it. Should we make the e2e tests run on every PR?

**Comment by dgkanatsios** [comment]
as discussed in yesterday's community meeting, we should update this thread with the design specific of the e2e testing. So, as a first step, we could do the following on
- run a shell script `e2e.sh` that would install kind and do `kind create cluster`
- it would also install brigade by using `make docker-build`,  `make helm-upgrade` with `kind load docker-image $(DOCKER_REGISTRY)/$*:$(IMAGE_TAG)` to load images to be used by kind
- same script would do `go run brig/cmd/main.go project create -f premadeproject.yaml` to create a Brigade project
- script could call a go program that would check if the corresponding Secret(s) are indeed created in the cluster, with the correct annotations etc.

I think this should be enough for the first version of the e2e testing. Subsequent versions could include setting up Generic/GitHub gateway and invoking them.
