### ISSUE TITLE
Local build targets / Build fails on Windows

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade#927]
#920 brought significant improvements to the build and release process.

However, there is one scenario where now using the Make targets to build locally became significantly more difficult is on Windows, including WSL.

on Windows:
```
make -f .\Makefile build-brig
docker run -it --rm -e SKIP_DOCKER=true -v $(pwd):/go/src/github.com/brigadecore/brigade -w /go/src/github.com/brigadecore/brigade quay.io/deis/lightweight-docker-go:v0.7.0 bash -c 'LDFLAGS="-X github.com/brigadecore/brigade/pkg/version.Version=5559a34-dirty" scripts/build-brig.sh'
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Mount denied:
The source path "C:/projects/go/src/github.com/brigadecore/brigade;C"
doesn't exist and is not known to Docker.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
make: *** [build-brig] Error 125
```

Because the build target is using `$(pwd)`, this fails on Windows, and because WSL can't mount directories in Docker properly, if you're on Windows it means the current build process doesn't work.

That being said, I used to use the local targets to build and test components locally quite a bit, `make brig` in particular, and generally without Docker being a requirement.

Apologies, I should have tested this as part of the the PR review for #920.

cc @krancour, @vdice

**Comment by krancour** [comment]
@radu-matei you can opt-out of the container by setting `SKIP_DOCKER=true`

**Comment by radu-matei** [comment]
Nice, thanks!

However, that solves for WSL, not for Windows only.

**Comment by krancour** [comment]
@radu-matei not sure why that doesn't solve for the Windows-only scenario. If `SKIP_DOCKER` is true, besides no container being used, `pwd` also would never be invoked.

> I used to use the local targets to build and test components locally quite a bit, make brig in particular, and generally without Docker being a requirement

As an aside, I feel the need to defend why I made things happen in containers (by default) in the first place. Without a container used as a sandbox for things like executing tests or building the brig CLI, success or failure of any task is dependent on the state of your system. What happens when a contributor has a different version of node? Or a different version of yarn? Or Go? Making tasks such as these execute in a container, by default, eliminate most variability...

Granted, this strategy isn't perfect, as you have uncovered, because there are "gotchas" do Docker on Windows or WSL, for instance, that don't manifest on Mac or Linux. I'm very willing to solve for that rather than give up on the notion of development tasks being executed, by default, in a container that is identical to the one that will be used in the actual CI/CD pipeline.

So, here, for instance, I think we can probably try and figure out how to modify the `DOCKER_CMD` variable according to host OS rather than give up on the idea.

Sound ok?
